// Auto-generated from gpu_particles_clear_cs.wgsl
// Do not edit manually

#pragma once

static const char gpu_particles_clear_cs_wgsl[] = 
"// Effekseer GPU Particles Clear Compute Shader (WGSL)\n// Equivalent to gpu_particles_clear_cs.fx\n\nstruct EmitterData {\n    flagBits: u32,\n    seed: u32,\n    particleHead: u32,\n    particleSize: u32,\n    trailHead: u32,\n    trailSize: u32,\n    trailPhase: u32,\n    nextEmitCount: u32,\n    totalEmitCount: u32,\n    emitPointCount: u32,\n    timeCount: f32,\n    timeStopped: f32,\n    reserved0: u32,\n    reserved1: u32,\n    deltaTime: f32,\n    color: u32,\n    transform: mat4x3<f32>,\n}\n\nstruct ComputeConstants {\n    coordinateReversed: u32,\n    reserved0: f32,\n    reserved1: f32,\n    reserved2: f32,\n}\n\nstruct ParameterData {\n    emitCount: i32,\n    emitPerFrame: i32,\n    emitOffset: f32,\n    padding0: u32,\n    lifeTime: vec2<f32>,\n    emitShapeType: u32,\n    emitRotationApplied: u32,\n    emitShapeData: array<vec4<f32>, 2>,\n    direction: vec3<f32>,\n    spread: f32,\n    initialSpeed: vec2<f32>,\n    damping: vec2<f32>,\n    angularOffset: array<vec4<f32>, 2>,\n    angularVelocity: array<vec4<f32>, 2>,\n    scaleData1: array<vec4<f32>, 2>,\n    scaleData2: array<vec4<f32>, 2>,\n    scaleEasing: vec3<f32>,\n    scaleFlags: u32,\n    gravity: vec3<f32>,\n    padding2: u32,\n    vortexCenter: vec3<f32>,\n    vortexRotation: f32,\n    vortexAxis: vec3<f32>,\n    vortexAttraction: f32,\n    turbulencePower: f32,\n    turbulenceSeed: u32,\n    turbulenceScale: f32,\n    turbulenceOctave: f32,\n    renderState: u32,\n    shapeType: u32,\n    shapeData: u32,\n    shapeSize: f32,\n    emissive: f32,\n    fadeIn: f32,\n    fadeOut: f32,\n    materialType: u32,\n    colorData: vec4<u32>,\n    colorEasing: vec3<f32>,\n    colorFlags: u32,\n}\n\n// Particle data structure (80 bytes per particle)\n// Stored as raw bytes in storage buffer\n\n@group(0) @binding(0)\nvar<uniform> constants: ComputeConstants;\n\n@group(0) @binding(1)\nvar<uniform> paramData: ParameterData;\n\n@group(0) @binding(2)\nvar<uniform> emitter: EmitterData;\n\n@group(1) @binding(0)\nvar<storage, read_write> particles: array<u32>;\n\n@compute @workgroup_size(256, 1, 1)\nfn main(@builtin(global_invocation_id) dtid: vec3<u32>) {\n    let particleID = emitter.particleHead + dtid.x;\n    let baseOffset = particleID * 20u; // 80 bytes / 4 bytes per u32 = 20 u32s\n    \n    // Clear particle data\n    // FlagBits = 0 (inactive)\n    particles[baseOffset + 0u] = 0u;\n    // Seed = 0\n    particles[baseOffset + 1u] = 0u;\n    // LifeAge = 0.0\n    particles[baseOffset + 2u] = 0u;\n    // InheritColor = 0\n    particles[baseOffset + 3u] = 0u;\n    // Color = 0\n    particles[baseOffset + 4u] = 0u;\n    // Direction = 0\n    particles[baseOffset + 5u] = 0u;\n    // Velocity (2 u32s)\n    particles[baseOffset + 6u] = 0u;\n    particles[baseOffset + 7u] = 0u;\n    // Transform (12 floats = 12 u32s)\n    for (var i = 0u; i < 12u; i = i + 1u) {\n        particles[baseOffset + 8u + i] = 0u;\n    }\n}\n";

static const int gpu_particles_clear_cs_wgsl_len = 2814;
