// Auto-generated from gpu_particles_render_ps.wgsl
// Do not edit manually

#pragma once

static const char gpu_particles_render_ps_wgsl[] = 
"// Effekseer GPU Particles Render Pixel Shader (WGSL)\n// Equivalent to gpu_particles_render_ps.fx\n\nstruct PSInput {\n    @location(0) uv: vec2<f32>,\n    @location(1) color: vec4<f32>,\n    @location(2) worldN: vec3<f32>,\n    @location(3) worldB: vec3<f32>,\n    @location(4) worldT: vec3<f32>,\n}\n\nstruct RenderConstants {\n    cameraPos: vec3<f32>,\n    coordinateReversed: u32,\n    cameraFront: vec3<f32>,\n    reserved1: f32,\n    lightDir: vec3<f32>,\n    reserved2: f32,\n    lightColor: vec4<f32>,\n    lightAmbient: vec4<f32>,\n    projMat: mat4x4<f32>,\n    cameraMat: mat4x4<f32>,\n    billboardMat: mat4x3<f32>,\n    yAxisFixedMat: mat4x3<f32>,\n}\n\nstruct ParameterData {\n    emitCount: i32,\n    emitPerFrame: i32,\n    emitOffset: f32,\n    padding0: u32,\n    lifeTime: vec2<f32>,\n    emitShapeType: u32,\n    emitRotationApplied: u32,\n    emitShapeData: array<vec4<f32>, 2>,\n    direction: vec3<f32>,\n    spread: f32,\n    initialSpeed: vec2<f32>,\n    damping: vec2<f32>,\n    angularOffset: array<vec4<f32>, 2>,\n    angularVelocity: array<vec4<f32>, 2>,\n    scaleData1: array<vec4<f32>, 2>,\n    scaleData2: array<vec4<f32>, 2>,\n    scaleEasing: vec3<f32>,\n    scaleFlags: u32,\n    gravity: vec3<f32>,\n    padding2: u32,\n    vortexCenter: vec3<f32>,\n    vortexRotation: f32,\n    vortexAxis: vec3<f32>,\n    vortexAttraction: f32,\n    turbulencePower: f32,\n    turbulenceSeed: u32,\n    turbulenceScale: f32,\n    turbulenceOctave: f32,\n    renderState: u32,\n    shapeType: u32,\n    shapeData: u32,\n    shapeSize: f32,\n    emissive: f32,\n    fadeIn: f32,\n    fadeOut: f32,\n    materialType: u32,\n    colorData: vec4<u32>,\n    colorEasing: vec3<f32>,\n    colorFlags: u32,\n}\n\n@group(0) @binding(0)\nvar<uniform> constants: RenderConstants;\n\n@group(0) @binding(1)\nvar<uniform> paramData: ParameterData;\n\n@group(1) @binding(0)\nvar colorTex: texture_2d<f32>;\n\n@group(1) @binding(1)\nvar colorSampler: sampler;\n\n@group(1) @binding(2)\nvar normalTex: texture_2d<f32>;\n\n@group(1) @binding(3)\nvar normalSampler: sampler;\n\n@fragment\nfn main(input: PSInput) -> @location(0) vec4<f32> {\n    var color = input.color * textureSample(colorTex, colorSampler, input.uv);\n    \n    // Lit material\n    if (paramData.materialType == 1u) {\n        let texNormal = textureSample(normalTex, normalSampler, input.uv).xyz * 2.0 - vec3<f32>(1.0);\n        let TBN = mat3x3<f32>(input.worldT, input.worldB, input.worldN);\n        let normal = normalize(texNormal * TBN);\n        let diffuse = max(dot(constants.lightDir, normal), 0.0);\n        color = vec4<f32>(\n            color.xyz * (constants.lightColor.xyz * diffuse + constants.lightAmbient.xyz),\n            color.w\n        );\n    }\n    \n    return color;\n}\n";

static const int gpu_particles_render_ps_wgsl_len = 2673;
